---
- hosts: mimosa_nodes
  become: true
  tasks:

    - name: Ensure Docker and Python SDK are installed
      package:
        name:
          - docker
          - python3-docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Dockerfile and app files to managed node
      copy:
        src: .
        dest: /opt/app_deploy/
        owner: root
        group: root
        mode: '0755'
    - name: Stop and remove old containers if running
      become: true
      shell: |
       docker stop tomcat-app || true
       docker rm tomcat-app || true
       docker stop mysql-db || true
       docker rm mysql-db || true
      ignore_errors: yes

    - name: Build Tomcat app image
      community.docker.docker_image:
        name: tomcat-custom
        build:
          path: /opt/app_deploy
        source: build

    - name: Run MySQL container
      community.docker.docker_container:
        name: mysql-db
        image: mysql:8
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: appdb
        ports:
          - "3306:3306"

    - name: Run Tomcat app container
      community.docker.docker_container:
        name: tomcat-app
        image: tomcat-custom
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        links:
          - mysql-db:mysql

