---
- hosts: mimosa_nodes
  become: true
  tasks:

    - name: Ensure Docker is installed
      package:
        name:
          - docker
          - python3-docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run MySQL container
      docker_container:
        name: mysql-db
        image: mysql:8
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: appdb
        ports:
          - "3306:3306"

    - name: Run Tomcat container
      docker_container:
        name: tomcat-app
        image: tomcat:9
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

