---
- name: Deploy Java + MySQL containers using Docker
  hosts: mimosa_nodes
  become: yes
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Install Docker if not installed
      yum:
        name: docker
        state: present
      when: docker_check.rc != 0

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker Python module is installed
      pip:
        name: docker
        executable: pip3

    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql
        source: pull

    - name: Run MySQL container
      community.docker.docker_container:
        name: mysql_db
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: myappdb
        ports:
          - "3306:3306"
        state: started
        restart_policy: always

    - name: Pull Java (openjdk) image
      community.docker.docker_image:
        name: openjdk
        source: pull

    - name: Copy application JAR
      copy:
        src: appdir/myapp.jar
        dest: /opt/myapp.jar

    - name: Run Java app container
      community.docker.docker_container:
        name: java_app
        image: openjdk
        command: "java -jar /opt/myapp.jar"
        volumes:
          - /opt/myapp.jar:/opt/myapp.jar
        ports:
          - "8080:8080"
        depends_on:
          - mysql_db
        state: started
        restart_policy: always
